//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMetaInformation
    {
        public int AccountMetaInformationId { get; set; }
        public int AccountId { get; set; }
        public string FatherName { get; set; }
        public string MothersName { get; set; }
        public int MaritalStatusId { get; set; }
        public string SpouceName { get; set; }
        public int BloodGroupsId { get; set; }
        public int GenderId { get; set; }
        public string CurrentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> JoiningDateTime { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
    }
}
