//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountExtProject
    {
        public int AccountExtProjectId { get; set; }
        public int AccountMetaProfessionalId { get; set; }
        public string ProjectTitle { get; set; }
        public string ShortDescription { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> ProjectStratedDate { get; set; }
        public Nullable<System.DateTime> ProjectCompletedDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
        public Nullable<int> AccountId { get; set; }
    
        public virtual AccountMetaProfessional AccountMetaProfessional { get; set; }
    }
}
