//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountMetaProfessional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccountMetaProfessional()
        {
            this.AccountExtEducations = new HashSet<AccountExtEducation>();
            this.AccountExtProfessionalActivities = new HashSet<AccountExtProfessionalActivity>();
            this.AccountExtProjects = new HashSet<AccountExtProject>();
            this.AccountExtPublications = new HashSet<AccountExtPublication>();
        }
    
        public int AccountMetaProfessionalId { get; set; }
        public int AccountId { get; set; }
        public string BackGround { get; set; }
        public string ResearchInterest { get; set; }
        public string PhdSuperVision { get; set; }
        public string Publication { get; set; }
        public int MediaContriBution { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string EntryBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountExtEducation> AccountExtEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountExtProfessionalActivity> AccountExtProfessionalActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountExtProject> AccountExtProjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountExtPublication> AccountExtPublications { get; set; }
    }
}
