//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountReferenceLinktable
    {
        public int AccountReferenceId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Facebook { get; set; }
        public string GooglePlus { get; set; }
        public string Twitter { get; set; }
        public string Linkedin { get; set; }
        public string Fax { get; set; }
        public string TelephoneNo { get; set; }
        public string MobileNo { get; set; }
    }
}
