//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int AccountId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNo { get; set; }
        public string TeleExchange { get; set; }
        public string Designation { get; set; }
        public string DepartmentSection { get; set; }
        public string LoginIdentity { get; set; }
        public string Password { get; set; }
        public int AccountsRoleId { get; set; }
        public string Pic { get; set; }
        public bool Status { get; set; }
        public Nullable<System.Guid> AccountHash { get; set; }
        public bool PartimeTeacher { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public bool Deactivate { get; set; }
        public string CauseOfDeactivate { get; set; }
        public bool TeporaryBlock { get; set; }
        public Nullable<System.DateTime> TemporaryBlockExpireDate { get; set; }
        public string LastPsswordChange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
