//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseForDepartment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseForDepartment()
        {
            this.CourseForStudentsAcademics = new HashSet<CourseForStudentsAcademic>();
            this.Sections = new HashSet<Section>();
        }
    
        public int CourseForDepartmentId { get; set; }
        public int SerializedSemesterId { get; set; }
        public int DepartmentId { get; set; }
        public string CourseType { get; set; }
        public string CourseCode { get; set; }
        public string CourseName { get; set; }
        public string PrerequisiteCourse { get; set; }
        public double Credit { get; set; }
        public bool Deactivate { get; set; }
        public string Note { get; set; }
        public int GradingSystemId { get; set; }
        public string Remarks { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseForStudentsAcademic> CourseForStudentsAcademics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
