//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Department()
        {
            this.CourseForDepartments = new HashSet<CourseForDepartment>();
            this.Semesters = new HashSet<Semester>();
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int DepartmentId { get; set; }
        public int SchoolId { get; set; }
        public string DepartmentName { get; set; }
        public string ShortName { get; set; }
        public int DepartmentCode { get; set; }
        public string DepartmentTitle { get; set; }
        public double TotalSemester { get; set; }
        public double TotalCredit { get; set; }
        public double AddmissionFee { get; set; }
        public double PerCreditCost { get; set; }
        public double LabFeePerSemester { get; set; }
        public double OtherFeePerSemister { get; set; }
        public double TotalCost { get; set; }
        public System.DateTime DateCreated { get; set; }
        public double RequiredCredit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseForDepartment> CourseForDepartments { get; set; }
        public virtual School School { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Semester> Semesters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
