//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentAdding
    {
        public int DocumentAddingId { get; set; }
        public string StudentId { get; set; }
        public bool SscCertificate { get; set; }
        public bool SscMarkSheet { get; set; }
        public bool HscCertificate { get; set; }
        public bool HscMarkSheet { get; set; }
        public bool DiplomaCertificate { get; set; }
        public bool DiplomaMarkSheet { get; set; }
        public bool Gce5Olavel { get; set; }
        public bool Gce5Alavel { get; set; }
        public bool BaBsCertificate { get; set; }
        public bool BaBsMarkSheet { get; set; }
        public bool MaMsCertificate { get; set; }
        public bool MaMsMarkSheet { get; set; }
        public bool TwoLettersofRecommendation { get; set; }
        public bool TwoStampSizePhotoGraph { get; set; }
        public bool SscTestimonial { get; set; }
        public bool HscTestimonial { get; set; }
    }
}
