//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradingSystem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GradingSystem()
        {
            this.CourseForStudentsAcademics = new HashSet<CourseForStudentsAcademic>();
            this.Sections = new HashSet<Section>();
        }
    
        public int GradingSystemId { get; set; }
        public int GradingCode { get; set; }
        public string GradingSystemName { get; set; }
        public double Attendance { get; set; }
        public double ClassTest { get; set; }
        public double MidTerm { get; set; }
        public double FinalTerm { get; set; }
        public double AttendancePercent { get; set; }
        public double ClassTestPercent { get; set; }
        public double MidTermPercent { get; set; }
        public double FinalTermPercent { get; set; }
        public bool SpecialGrading { get; set; }
        public string SpecPassGrade { get; set; }
        public string SpecFailGrade { get; set; }
        public double MinMarkToPass { get; set; }
        public bool ImpactOffResult { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseForStudentsAcademic> CourseForStudentsAcademics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Section> Sections { get; set; }
    }
}
