//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int LoginHistoryId { get; set; }
        public int AccountId { get; set; }
        public string EntryTime { get; set; }
        public string LastVisitedPage { get; set; }
        public string PcAddress { get; set; }
        public string DeviceType { get; set; }
        public string Browser { get; set; }
    }
}
