//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionId { get; set; }
        public string SectionName { get; set; }
        public int CourseForDepartmentId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public bool Status { get; set; }
        public int SemesterId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> GradingSystemId { get; set; }
        public string ShortNote { get; set; }
        public bool HighLight { get; set; }
        public Nullable<System.DateTime> ExpireDateTime { get; set; }
        public bool MidTermEx { get; set; }
        public bool FinalTermEx { get; set; }
        public bool EvaluationPossible { get; set; }
        public bool ConfirmSubmitByFaculty { get; set; }
        public Nullable<System.DateTime> SumissionDate { get; set; }
        public bool RevisedStat { get; set; }
        public Nullable<System.DateTime> ResubmitDate { get; set; }
        public bool NonCreditMarkSubmit { get; set; }
    
        public virtual GradingSystem GradingSystem { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual CourseForDepartment CourseForDepartment { get; set; }
    }
}
