//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StudentInfoId { get; set; }
        public string StudentId { get; set; }
        public string StudentName { get; set; }
        public string FathersName { get; set; }
        public string MothersName { get; set; }
        public string PresentAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public int BloodGroupsId { get; set; }
        public int MaritalStatusId { get; set; }
        public int GenderId { get; set; }
        public string Nationality { get; set; }
        public string SkillInOtherfield { get; set; }
        public string LocalGuardianName { get; set; }
        public string LocalGuardianRelationship { get; set; }
        public string LocalGuardianAddress { get; set; }
        public string LocalGuardianContact { get; set; }
        public string EmailAddress { get; set; }
        public string PresentDistrict { get; set; }
        public string PresentPostalCode { get; set; }
        public string ParmanentDistrict { get; set; }
        public string ParmanentPostalCode { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
    
        public virtual BloodGroup BloodGroup { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
    }
}
