//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAcademicInfo
    {
        public int StudentAcademicInfoId { get; set; }
        public string StudentId { get; set; }
        public string NameOfExamination { get; set; }
        public string StartingSession { get; set; }
        public string UniversityBoard { get; set; }
        public string PassingYear { get; set; }
        public string Result { get; set; }
        public string Group { get; set; }
    }
}
