//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttatchedFileCategory
    {
        public int StudentAttatchedFileCategoryId { get; set; }
        public string FirstName { get; set; }
        public string CategoryName { get; set; }
        public bool VisibleStudent { get; set; }
        public bool VisibleCustom { get; set; }
        public bool VisibleAdmin { get; set; }
        public string Remarks { get; set; }
    }
}
