//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PauFacultyPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivity
    {
        public int UserActivityId { get; set; }
        public int UserActivityTypeId { get; set; }
        public int AccountId { get; set; }
        public string Activity { get; set; }
        public string StudentId { get; set; }
        public Nullable<System.DateTime> ActivityTime { get; set; }
        public bool Seen { get; set; }
        public string ComputerIp { get; set; }
    }
}
